version: '3.8'

services:
  myapp:
    container_name: myapp_subbranch
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/growlf/toolbox:testing
    environment:
      - TESTVAR=${TESTVAR:-app}
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    volumes:
      - ${HOME}/.gitconfig:/home/ubuntu/.gitconfig
      - ${HOME}/.ssh:/home/ubuntu/.ssh
      - ${PWD}:/app
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
